# Generated by Django 2.2.2 on 2019-06-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=170)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=19)),
                ('new_price', models.IntegerField()),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
