# Generated by Django 2.2.2 on 2019-06-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190620_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='select',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], default='', max_length=150),
            preserve_default=False,
        ),
    ]
