# Generated by Django 2.2.2 on 2019-06-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_select'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='select',
            new_name='color',
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], default='', max_length=150),
            preserve_default=False,
        ),
    ]
