# Generated by Django 2.2.2 on 2019-06-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190620_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attr',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], default='size', max_length=150),
        ),
    ]
