# Generated by Django 2.2.2 on 2019-06-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='img',
            field=models.ImageField(default='', upload_to='pic_folder/'),
            preserve_default=False,
        ),
    ]
